#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx
sudo apt-get install -y git

sudo apt-get install -y python-pip

sudo pip install virtualenv virtualenvwrapper
source /usr/local/bin/virtualenvwrapper.sh

# Add to .bashrc
# Virtualenvwrapper
#export WORKON_HOME=$HOME/.virtualenvs
#source /usr/local/bin/virtualenvwrapper.sh


mkvirtualenv gabinet
cd ~
mkdir projects;cd projects
git clone git@github.com:BStalewski/gabinet.git;cd gabinet

pip install -r pip_requirements

cd /etc/nginx/sites-available
sudo ln -s ~/projects/gabinet/gabinet/conf/production/gabinet gabinet
cd ../sites-enabled/
sudo ln -s ../sites-available/gabinet .
sudo rm default

cd /etc/supervisor/conf.d/
sudo ln -s ~/projects/gabinet/gabinet/conf/production/gabinet_supervisor.conf .
sudo ln -s ~/projects/gabinet/gabinet/conf/production/nginx_supervisor.conf .

# add "daemon off" to nginx.conf file
cd /etc/nginx/
sudo vim nginx.conf # add this line

sudo nginx -s stop
sudo update-rc.d -f nginx disable

sudo mkdir -p /var/www/logs

sudo mkdir -p /var/www/gabinet
cd /var/www/gabinet
sudo ln -s /home/ubuntu/projects/gabinet/gabinet/collected_static collected_static
